### PR TITLE
Updated sensor for 0.92

### PR DESCRIPTION
**Pull request by dimmanramone**

### CODE REVIEW

**Comment by DSorlov** [comment]
As this will break older (pre 0.92) in loosing the dependency I decided against merging this in right now. I took the liberty however and making your changes directly in the :dev branch and attributing you there instead so that it can be in the next release (see [419353c](https://github.com/DSorlov/ha-sensor-sl/commit/419353cb78ede25e98fa482261607b3bf5c27fec))

**Comment by dimmanramone** [comment]
I missed that there is a dev branch now 😀

**Comment by DSorlov** [comment]
> I missed that there is a dev branch now 😀

Yeah; I learned from my mistakes the last time I broke stuff for everyone. Tried to be lazy and only have one branch but hey.. =)

**Comment by dimmanramone** [comment]
That's good. Then next time I'll make a PR on dev.

**Pull request closed without merging**
